version: "3.9"

services:
  web:
    image: mrcavin/django-image:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: gunicorn crm.wsgi:application --bind 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/sites-available/crm.conf:/etc/nginx/conf.d/crm.conf
      - static_volume:/staticfiles

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
  static_volume:
