# Generated by Django 5.2 on 2025-05-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='inter_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
